DROP SEQUENCE  CMPL_SEQ_CATEGORY;
DROP SEQUENCE  CMPL_SEQ_DEPARTMENT;
DROP SEQUENCE  CMPL_SEQ_DOC_TYPE;
DROP SEQUENCE  CMPL_SEQ_ATTACHED_FILE;
DROP SEQUENCE  CMPL_SEQ_COMPLAINT;
DROP SEQUENCE  CMPL_SEQ_COMPLAINT_AUTHOR;

DROP trigger CMPL_INC_SEQ_CATEGORY;
DROP trigger CMPL_INC_SEQ_DEPARTMENT;
DROP trigger CMPL_INC_SEQ_DOC_TYPE;
DROP trigger CMPL_INC_SEQ_ATTACHED_FILE;
DROP trigger CMPL_INC_SEQ_COMPLAINT;
DROP trigger CMPL_INC_SEQ_COMPLAINT_AUTHOR;

alter table CMPL_ATTACHED_FILE
   drop constraint FK_CMPL_ATT_REL_COMPL_CMPL_COM;

alter table CMPL_ATTACHED_FILE
   drop constraint FK_CMPL_ATT_REL_DOC_T_CMPL_DOC;

alter table CMPL_COMPLAINT
   drop constraint FK_CMPL_COM_REL_AUTHO_CMPL_COM;

alter table CMPL_COMPLAINT
   drop constraint FK_CMPL_COM_REL_CATEG_CMPL_CAT;

alter table CMPL_COMPLAINT
   drop constraint FK_CMPL_COM_REL_DEPAR_CMPL_DEP;


drop index INDEX_ATTACHED_FILE_INSERTED;

drop index INDEX_ATTACHED_FILE_HTTP_SESSI;

drop index REL_COMPLAINT_TO_FILE_FK;

drop index REL_DOC_TYPE_TO_FILE_FK;

drop table CMPL_ATTACHED_FILE cascade constraints;

drop table CMPL_CATEGORY cascade constraints;

drop index INDEX_COMPLAINT_EMAIL;

drop index INDEX_CLIENT_IP;

drop index INDEX_COMPLAINT_INSERTED;

drop index INDEX_COMPLAINT_HTTP_SESSION_I;

drop index REL_AUTHOR_TO_COMPLAINT_FK;

drop index REL_CATEGORY_TO_COMPLAINT_FK;

drop index REL_DEPARTMENT_TO_COMPLAINT_FK;

drop table CMPL_COMPLAINT cascade constraints;

drop table CMPL_COMPLAINT_AUTHOR cascade constraints;

drop index INDEX_DEPARTMENT_CODE;

drop table CMPL_DEPARTMENT cascade constraints;

drop table CMPL_DOC_TYPE cascade constraints;


