INSERT INTO CMPL_COMPLAINT_AUTHOR (COMPLAINT_AUTHOR_NAME) VALUES ('Физическое лицо');
INSERT INTO CMPL_COMPLAINT_AUTHOR (COMPLAINT_AUTHOR_NAME) VALUES ('Юридическое лицо');
INSERT INTO CMPL_COMPLAINT_AUTHOR (COMPLAINT_AUTHOR_NAME) VALUES ('Представитель физического лица');
INSERT INTO CMPL_COMPLAINT_AUTHOR (COMPLAINT_AUTHOR_NAME) VALUES ('Представитель юридического лица');

commit;

INSERT INTO CMPL_CATEGORY (CATEGORY_NAME) VALUES ('Вопросы, связанные с государственной регистрацией прав на недвижимое имущество и сделок с ним и государственным кадастром недвижимости');
INSERT INTO CMPL_CATEGORY (CATEGORY_NAME) VALUES ('Вопросы, связанные с предоставлением информации из ЕГРП и ГКН');
INSERT INTO CMPL_CATEGORY (CATEGORY_NAME) VALUES ('Вопросы срыва сроков предоставления сведений по ранее направленным запросам и функционированию Портала услуг Росреестра');
INSERT INTO CMPL_CATEGORY (CATEGORY_NAME) VALUES ('Вопросы, связанные с деятельностью саморегулируемых организаций арбитражных управляющих');
INSERT INTO CMPL_CATEGORY (CATEGORY_NAME) VALUES ('Вопросы, связанные с кадастровой оценкой объектов недвижимости');
INSERT INTO CMPL_CATEGORY (CATEGORY_NAME) VALUES ('Вопросы, связанные с государственным земельным контролем, землеустройством и мониторингом земель');
INSERT INTO CMPL_CATEGORY (CATEGORY_NAME) VALUES ('Вопросы, связанные с техническим учетом и инвентаризацией объектов капитального строительства');
INSERT INTO CMPL_CATEGORY (CATEGORY_NAME) VALUES ('Вопросы, связанные с геодезической, картографической и навигационной деятельностью');
INSERT INTO CMPL_CATEGORY (CATEGORY_NAME) VALUES ('Жалобы на организацию работы (отказ в приеме и выдаче документов, время ожидания в очереди превышает установленное административным регламентом, отсутствие предварительной записи (плохая организация), некорректное обслуживание заявителя на приеме и др.)');
INSERT INTO CMPL_CATEGORY (CATEGORY_NAME) VALUES ('Жалобы на работу руководителей (специалистов) территориальных органов Росреестра');
INSERT INTO CMPL_CATEGORY (CATEGORY_NAME) VALUES ('Предложения по совершенствованию деятельности Росреестра и его территориальных органов');
INSERT INTO CMPL_CATEGORY (CATEGORY_NAME) VALUES ('Другие вопросы, относящиеся к компетенции Росреестра');

commit;

INSERT INTO CMPL_DOC_TYPE (DOC_TYPE_NAME) VALUES ('Документ подтверждающий полномочия');
INSERT INTO CMPL_DOC_TYPE (DOC_TYPE_NAME) VALUES ('Правоустанавливающий документ');
INSERT INTO CMPL_DOC_TYPE (DOC_TYPE_NAME) VALUES ('Иное');

commit;

INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('00', 'Центральный аппарат Федеральной службы государственной регистрации, кадастра и картографии (Росреестра)', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('01', 'Управление Росреестра по Республике Адыгея', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('02', 'Управление Росреестра по Республике Башкортостан', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('03', 'Управление Росреестра по Республике Бурятия', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('04', 'Управление Росреестра по Республике Алтай', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('05', 'Управление Росреестра по Республике Дагестан', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('06', 'Управление Росреестра по Республике Ингушетии', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('07', 'Управление Росреестра по Кабардино-Балкарской Республике', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('08', 'Управление Росреестра по Республике Калмыкия', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('09', 'Управление Росреестра по Карачаево-Черкесской Республике', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('10', 'Управление Росреестра по Республике Карелия', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('11', 'Управление Росреестра по Республике Коми', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('12', 'Управление Росреестра по Республика Марий Эл', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('13', 'Управление Росреестра по Республике Мордовия', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('14', 'Управление Росреестра по Республика Саха (Якутия)', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('15', 'Управление Росреестра по Республике Северная Осетия', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('16', 'Управление Росреестра по Республике Татарстан', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('17', 'Управление Росреестра по Республике Тыва', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('18', 'Управление Росреестра по Удмуртской Республике', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('19', 'Управление Росреестра по Республика Хакасия', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('20', 'Управление Росреестра по Чеченской Республике', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('21', 'Управление Росреестра по Чувашской Республике', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('22', 'Управление Росреестра по Алтайскому краю', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('23', 'Управление Росреестра по Краснодарскому краю', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('24', 'Управление Росреестра по Красноярскому краю', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('25', 'Управление Росреестра по Приморскому краю', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('26', 'Управление Росреестра по Ставропольскому краю', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('27', 'Управление Росреестра по Хабаровскому краю', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('28', 'Управление Росреестра по Амурской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('29', 'Управление Росреестра по Архангельской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('30', 'Управление Росреестра по Астраханской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('31', 'Управление Росреестра по Белгородской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('32', 'Управление Росреестра по Брянской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('33', 'Управление Росреестра по Владимирской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('34', 'Управление Росреестра по Волгоградской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('35', 'Управление Росреестра по Вологодской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('36', 'Управление Росреестра по Воронежской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('37', 'Управление Росреестра по Ивановской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('38', 'Управление Росреестра по Иркутской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('39', 'Управление Росреестра по Калининградской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('40', 'Управление Росреестра по Калужской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('41', 'Управление Росреестра по Камчатскому краю', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('42', 'Управление Росреестра по Кемеровской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('43', 'Управление Росреестра по Кировской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('44', 'Управление Росреестра по Костромской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('45', 'Управление Росреестра по Курганской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('46', 'Управление Росреестра по Курской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('47', 'Управление Росреестра по Ленинградской области', 'asergeev1970@gmail.com');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('48', 'Управление Росреестра по Липецкой области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('49', 'Управление Росреестра по Магаданской области и Чукотскому АО', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('50', 'Управление Росреестра по Московской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('51', 'Управление Росреестра по Мурманской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('52', 'Управление Росреестра по Нижегородской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('53', 'Управление Росреестра по Новгородской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('54', 'Управление Росреестра по Новосибирской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('55', 'Управление Росреестра по Омской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('56', 'Управление Росреестра по Оренбургской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('57', 'Управление Росреестра по Орловской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('58', 'Управление Росреестра по Пензенской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('59', 'Управление Росреестра по Пермскому краю', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('60', 'Управление Росреестра по Псковской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('61', 'Управление Росреестра по Ростовской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('62', 'Управление Росреестра по Рязанской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('63', 'Управление Росреестра по Самарской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('64', 'Управление Росреестра по Саратовской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('65', 'Управление Росреестра по Сахалинской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('66', 'Управление Росреестра по Свердловской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('67', 'Управление Росреестра по Смоленской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('68', 'Управление Росреестра по Тамбовской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('69', 'Управление Росреестра по Тверской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('70', 'Управление Росреестра по Томской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('71', 'Управление Росреестра по Тульской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('72', 'Управление Росреестра по Тюменской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('73', 'Управление Росреестра по Ульяновской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('74', 'Управление Росреестра по Челябинской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('75', 'Управление Росреестра по Забайкальскому Краю', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('76', 'Управление Росреестра по Ярославской области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('77', 'Управление Росреестра по городу Москве', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('78', 'Управление Росреестра по Санкт-Петербургу', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('79', 'Управление Росреестра по Еврейской автономной области', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('80', 'Управление Росреестра по Ханты-Мансийскому автономному округу', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('81', 'Управление Росреестра по Ямало-Ненецкому автономному округу', 'corop@list.ru');
INSERT INTO CMPL_DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME, DEPARTMENT_EMAIL) VALUES ('82', 'Управление Росреестра по Северо-Кавказскому ФО', 'corop@list.ru');

commit;
